name: Pull Request Cancel Example
on: [pull_request]

jobs:
  check-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running now'
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - uses: avdeev-dima-tutu/cancel-previous-pull-request@master
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - run: echo 'wasnt cancelled'
